package hospitalproject;


import hospitalproject.Connectionprovider;
import java.awt.Checkbox;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class Bills extends javax.swing.JFrame {

    /**
     * Creates new form Bills
     */
    public Bills() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnami = new javax.swing.JTextField();
        Clac = new javax.swing.JButton();
        cward = new javax.swing.JCheckBox();
        lno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        no = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        medbil = new javax.swing.JTextField();
        lward = new javax.swing.JLabel();
        ward = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ttbill = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        psearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setMinimumSize(new java.awt.Dimension(880, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Bills");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 80, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Patient Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 120, -1));

        patientID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        patientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIDActionPerformed(evt);
            }
        });
        getContentPane().add(patientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 180, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Patient Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Ward");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 60, 30));

        pnami.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnamiActionPerformed(evt);
            }
        });
        getContentPane().add(pnami, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 180, -1));

        Clac.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Clac.setText("Calc");
        Clac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClacActionPerformed(evt);
            }
        });
        getContentPane().add(Clac, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, 30));

        cward.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cwardActionPerformed(evt);
            }
        });
        getContentPane().add(cward, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 30, 30));

        lno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lno.setForeground(new java.awt.Color(51, 51, 255));
        lno.setText("No .Day");
        getContentPane().add(lno, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 80, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 0, 20));

        no.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 30, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Medical bill");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        medbil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        medbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medbilActionPerformed(evt);
            }
        });
        getContentPane().add(medbil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 70, -1));

        lward.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lward.setForeground(new java.awt.Color(51, 51, 255));
        lward.setText("ward bill");
        getContentPane().add(lward, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        ward.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardActionPerformed(evt);
            }
        });
        getContentPane().add(ward, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 90, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Total bill");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        ttbill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(ttbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 70, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        psearch.setText("Search");
        psearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psearchActionPerformed(evt);
            }
        });
        getContentPane().add(psearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dave\\Downloads\\pexels-daniel-frank-305568.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIDActionPerformed

    private void pnamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnamiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnamiActionPerformed
    
    private void ClacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClacActionPerformed
        // TODO add your handling code here:
        int  totalbill;
        int bill = Integer.parseInt(medbil.getText());
        int ward1 ;
        int  no1 = Integer.parseInt(no.getText());
        ward1=no1 * 550;
        totalbill = bill + ward1;
        ward.setText(String.valueOf(ward1));
        ttbill.setText(String.valueOf(totalbill));
       
       
        System.out.println(totalbill);
    }//GEN-LAST:event_ClacActionPerformed

    private void cwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cwardActionPerformed
        // TODO add your handling code here:
        
        if(cward.isSelected())
        {
          lward.setVisible(true);
          ward.setVisible(true);
          lno.setVisible(true);
          no.setVisible(true);
        }
        else{
        no.setText(String.valueOf(0));
          lward.setVisible(false);
          ward.setVisible(false);
          lno.setVisible(false);
          no.setVisible(false);
        }
    }//GEN-LAST:event_cwardActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_noActionPerformed

    private void medbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medbilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medbilActionPerformed

    private void wardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_wardActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String pid=patientID.getText();
        String med=medbil.getText();
        String wardd=ward.getText();
        String total=ttbill.getText();
        
        try{
        Connection conn = Connectionprovider.getCon();
            Statement st = conn.createStatement();
            String insert = "INSERT INTO `bill`(`pid`, `medbill`, `wardbill`, `totalbill`) VALUES('"+pid+"','"+med+"','"+wardd+"','"+total+"')";
            st.executeUpdate(insert);
            JOptionPane.showMessageDialog(null, "Successfully Saved");
            setVisible(false);
            new home().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "enter correct info");
                        System.err.println(e);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void psearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psearchActionPerformed
        // TODO add your handling code here:
        String patientid=patientID.getText();
        try {
            Connection conn=Connectionprovider.getCon();
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from `newpatient` where pid='"+patientid+"'");
             if (rs.next()) {
 
                String name = rs.getString("pname");
               
                pnami.setText(name);
            }
             else{
                 JOptionPane.showMessageDialog(null, "No Record found");
             }
            
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_psearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clac;
    private javax.swing.JCheckBox cward;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lno;
    private javax.swing.JLabel lward;
    private javax.swing.JTextField medbil;
    private javax.swing.JTextField no;
    private javax.swing.JTextField patientID;
    private javax.swing.JTextField pnami;
    private javax.swing.JButton psearch;
    private javax.swing.JTextField ttbill;
    private javax.swing.JTextField ward;
    // End of variables declaration//GEN-END:variables
}
